import { type FormEvent, useState } from "react";
import { Pencil, Plus } from "lucide-react";
import { Field, Input } from "../../components/ui";
import { useAtualizarEmpresaSankhya, useCriarEmpresaSankhya, useEmpresasSankhya } from "../../hooks/useConfiguracoes";
import type { EmpresaSankhya, EmpresaSankhyaInput } from "../../types/configuracoes";
import { buttonPrimary, Feedback, Section, Toggle } from "./shared";

const modial: EmpresaSankhyaInput = { codigo_empresa_sankhya: "1", razao_social: "Modial Comercio de Artigos Funerarios LTDA", cnpj: "04917818000124", ativa: true };

export function EmpresasSankhyaSection() {
  const query=useEmpresasSankhya(); const criar=useCriarEmpresaSankhya(); const atualizar=useAtualizarEmpresaSankhya();
  const [form,setForm]=useState<EmpresaSankhyaInput>(modial); const [edicao,setEdicao]=useState<string|null>(null);
  const mutacao=edicao?atualizar:criar;
  const alterar=(campo:keyof EmpresaSankhyaInput,valor:string|boolean)=>setForm(d=>({...d,[campo]:valor}));
  const novo=()=>{setEdicao(null);setForm({codigo_empresa_sankhya:"",razao_social:"",cnpj:"",ativa:true});};
  const editar=(empresa:EmpresaSankhya)=>{setEdicao(empresa.id);setForm({codigo_empresa_sankhya:empresa.codigo_empresa_sankhya,razao_social:empresa.razao_social,cnpj:empresa.cnpj,ativa:empresa.ativa});};
  async function submit(e:FormEvent){e.preventDefault();if(edicao)await atualizar.mutateAsync({id:edicao,dados:form});else await criar.mutateAsync(form);novo();}
  return <div className="space-y-4"><Section title="Empresas Sankhya" description="Cadastre o CODEMP enviado pelo Sankhya para identificar a empresa solicitante da cotação."><form onSubmit={submit} className="grid gap-4 md:grid-cols-[160px_1fr_220px]"><Field label="CODEMP"><Input required value={form.codigo_empresa_sankhya} onChange={e=>alterar("codigo_empresa_sankhya",e.target.value)} placeholder="Ex.: 1" /></Field><Field label="Razão social"><Input required value={form.razao_social} onChange={e=>alterar("razao_social",e.target.value)} /></Field><Field label="CNPJ"><Input required value={form.cnpj} onChange={e=>alterar("cnpj",e.target.value)} placeholder="00.000.000/0000-00" /></Field><div className="md:col-span-3 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-4"><Toggle checked={form.ativa} onChange={v=>alterar("ativa",v)} label="Empresa ativa"/><div className="flex items-center gap-3"><Feedback error={mutacao.error} success={mutacao.isSuccess}/>{edicao&&<button type="button" onClick={novo} className="h-9 rounded border border-border px-4 text-sm">Cancelar</button>}<button disabled={mutacao.isPending} className={buttonPrimary}>{mutacao.isPending?"Salvando...":edicao?"Salvar alterações":"Adicionar empresa"}</button></div></div></form></Section><Section title="CODEMP cadastrados" description="Somente empresas ativas podem solicitar cotações pela integração.">{query.isLoading?<p className="text-sm text-text-secondary">Carregando empresas...</p>:query.data?.length?<div className="overflow-x-auto rounded border border-border"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-surface2 text-xs text-text-secondary"><tr><th className="px-4 py-3">CODEMP</th><th className="px-4 py-3">Razão social</th><th className="px-4 py-3">CNPJ</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Ação</th></tr></thead><tbody>{query.data.map(empresa=><tr key={empresa.id} className="border-t border-border"><td className="px-4 py-3 font-mono text-state-info">{empresa.codigo_empresa_sankhya}</td><td className="px-4 py-3">{empresa.razao_social}</td><td className="px-4 py-3 font-mono">{empresa.cnpj}</td><td className="px-4 py-3">{empresa.ativa?"Ativa":"Inativa"}</td><td className="px-4 py-3 text-right"><button type="button" onClick={()=>editar(empresa)} className="inline-flex items-center gap-2 rounded border border-border px-3 py-2 text-xs"><Pencil size={13}/>Editar</button></td></tr>)}</tbody></table></div>:<div className="flex items-center gap-2 rounded border border-dashed border-border p-4 text-sm text-text-secondary"><Plus size={15}/>Nenhuma empresa cadastrada.</div>}</Section></div>;
}
