import { useState } from "react";
import { X } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { getErrorMessage } from "../../api/client";
import { Field, Input } from "../../components/ui";
import { transportadoraService } from "../../services/transportadoraService";

export function CadastroManualTransportadora({onClose,onBack}:{onClose:()=>void;onBack:()=>void}){
  const queryClient=useQueryClient();const [busy,setBusy]=useState(false),[error,setError]=useState("");
  const [form,setForm]=useState({nome:"",razao_social:"",cnpj_cpf:"",segmento:"Transporte rodoviário de cargas"});
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{await transportadoraService.criar({...form,tipo_integracao:"n8n",metodo_calculo:"manual",ativa:false});await Promise.all([queryClient.invalidateQueries({queryKey:["transportadoras"]}),queryClient.invalidateQueries({queryKey:["transportadoras","cards"]}),queryClient.invalidateQueries({queryKey:["transportadoras","stats"]})]);onClose()}catch(cause){setError(getErrorMessage(cause,"Não foi possível cadastrar a transportadora."))}finally{setBusy(false)}}
  return <div className="fixed inset-0 z-50 flex items-start justify-center bg-black/75 p-4 pt-[8vh]" role="dialog" aria-modal="true"><form onSubmit={event=>void submit(event)} className="w-full max-w-xl rounded-lg border border-border bg-surface shadow-2xl"><header className="flex justify-between border-b border-border p-5"><div><h2 className="font-semibold">Cadastro manual</h2><p className="mt-1 text-xs text-text-secondary">A transportadora será criada inativa.</p></div><button type="button" onClick={onClose} aria-label="Fechar" className="rounded border border-border p-2"><X size={15}/></button></header><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Nome fantasia"><Input required value={form.nome} onChange={event=>setForm({...form,nome:event.target.value})}/></Field><Field label="Razão social"><Input required value={form.razao_social} onChange={event=>setForm({...form,razao_social:event.target.value})}/></Field><Field label="CNPJ"><Input required value={form.cnpj_cpf} onChange={event=>setForm({...form,cnpj_cpf:event.target.value})}/></Field><Field label="Segmento"><Input required value={form.segmento} onChange={event=>setForm({...form,segmento:event.target.value})}/></Field>{error&&<p className="sm:col-span-2 rounded border border-state-error/40 bg-state-error/10 p-3 text-sm text-state-error">{error}</p>}</div><footer className="flex justify-between border-t border-border p-5"><button type="button" onClick={onBack} className="rounded border border-border px-4 py-2 text-sm">Voltar</button><button disabled={busy} className="rounded bg-state-info px-4 py-2 text-sm text-white disabled:opacity-50">{busy?"Cadastrando...":"Cadastrar transportadora"}</button></footer></form></div>
}
