import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { Badge, Input } from "../../components/ui";
import { getErrorMessage } from "../../api/client";
import { transportadoraService } from "../../services/transportadoraService";
import type { CarrierIntegration, CarrierSummary, CoverageCheck, EnrichmentBranch, EnrichmentCoverage, EnrichmentEvidence, EnrichmentIntegration, EnrichmentSource, Transportadora } from "../../types/transportadora";

type Tab="overview"|"coverage"|"integrations"|"branches"|"tables"|"sources"|"performance";
const integrationCategories=[["API_REST","API REST"],["API_SOAP","WebService SOAP"],["WEBSERVICE","WebService"],["SSW","SSW"],["SENIOR","TMS Senior"],["EDI","EDI"],["PORTAL","Portal de cotação"],["TABELA","Tabela de frete"]] as const;
const labels:Record<Tab,string>={overview:"Visão geral",coverage:"Cobertura",integrations:"Integrações",branches:"Filiais",tables:"Tabelas",sources:"Fontes",performance:"Desempenho"};
const empty={coverage:[] as EnrichmentCoverage[],integrations:[] as EnrichmentIntegration[],branches:[] as EnrichmentBranch[],sources:[] as EnrichmentSource[],evidence:[] as EnrichmentEvidence[],configured:[] as CarrierIntegration[]};

export function CarrierDetails({carrier,summary,onClose,onConfigure,onTables}:{carrier:Transportadora;summary?:CarrierSummary;onClose:()=>void;onConfigure:()=>void;onTables:()=>void}){
  const [tab,setTab]=useState<Tab>("overview"); const [data,setData]=useState(empty); const [loaded,setLoaded]=useState<Set<Tab>>(new Set()); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [origin,setOrigin]=useState(""); const [destination,setDestination]=useState(""); const [coverageResult,setCoverageResult]=useState<CoverageCheck|null>(null);
  useEffect(()=>{if(tab==="overview"||tab==="performance"||loaded.has(tab))return;setLoading(true);setError("");const request=tab==="coverage"?transportadoraService.listarCobertura(carrier.id):tab==="integrations"?Promise.all([transportadoraService.listarIntegracoesDescobertas(carrier.id),transportadoraService.listarIntegracoes(carrier.id)]):tab==="branches"?transportadoraService.listarFiliais(carrier.id):tab==="sources"?Promise.all([transportadoraService.listarFontes(carrier.id),transportadoraService.listarEvidencias(carrier.id)]):transportadoraService.listarIntegracoesDescobertas(carrier.id);request.then(result=>{setData(current=>tab==="coverage"?{...current,coverage:result as EnrichmentCoverage[]}:tab==="integrations"?{...current,integrations:(result as [EnrichmentIntegration[],CarrierIntegration[]])[0],configured:(result as [EnrichmentIntegration[],CarrierIntegration[]])[1]}:tab==="branches"?{...current,branches:result as EnrichmentBranch[]}:tab==="sources"?{...current,sources:(result as [EnrichmentSource[],EnrichmentEvidence[]])[0],evidence:(result as [EnrichmentSource[],EnrichmentEvidence[]])[1]}:{...current,integrations:result as EnrichmentIntegration[]});setLoaded(current=>new Set(current).add(tab));}).catch(error=>setError(getErrorMessage(error,"Não foi possível carregar esta seção."))).finally(()=>setLoading(false));},[tab,carrier.id,loaded]);
  const score=summary?.confidence_score==null?null:Math.round(summary.confidence_score*100);
  const configuredTypes=new Set<string>(data.configured.filter(item=>["configured","validated"].includes(item.status)).flatMap(item=>item.integration_type==="API"?["API","API_REST","API_SOAP","WEBSERVICE"]:item.integration_type==="TABLE"?["TABLE","TABELA"]:[item.integration_type]));
  async function verify(){setError("");try{setCoverageResult(await transportadoraService.verificarCobertura(carrier.id,origin,destination));}catch(error){setError(getErrorMessage(error,"Não foi possível verificar a cobertura."));}}
  return <div className="fixed inset-0 z-50 overflow-auto bg-black/70 p-3 sm:p-6"><section className="mx-auto min-h-[70vh] max-w-5xl rounded-lg border border-border bg-surface shadow-xl"><header className="flex items-start justify-between border-b border-border p-4 sm:p-5"><div><h2 className="font-semibold">{carrier.nome}</h2><p className="mt-1 text-xs text-text-secondary">Inteligência da transportadora · {summary?.completion_percent||0}% enriquecida</p></div><button aria-label="Fechar" onClick={onClose} className="rounded border border-border p-2 hover:bg-surface2"><X size={16}/></button></header>
    <nav className="flex overflow-x-auto border-b border-border px-3">{(Object.keys(labels) as Tab[]).map(item=><button key={item} onClick={()=>{setError("");setCoverageResult(null);setTab(item)}} className={`whitespace-nowrap border-b-2 px-3 py-3 text-xs ${tab===item?"border-state-info text-text-primary":"border-transparent text-text-secondary"}`}>{labels[item]}</button>)}</nav>
    <div className="p-4 sm:p-5">{loading&&<div className="space-y-2 animate-pulse"><div className="h-12 rounded bg-surface2"/><div className="h-20 rounded bg-surface2"/></div>}{error&&<div className="rounded border border-state-error/30 p-3 text-sm text-state-error">{error} <button onClick={()=>setLoaded(current=>{const next=new Set(current);next.delete(tab);return next;})} className="ml-2 underline">Tentar novamente</button></div>}
      {!loading&&!error&&tab==="overview"&&<div className="grid gap-5 sm:grid-cols-2"><Info title="Dados cadastrais" rows={[["Razão social",carrier.razao_social],["Nome fantasia",carrier.nome_fantasia],["CNPJ",carrier.cnpj_cpf],["RNTRC",carrier.rntrc],["Cidade / UF",[carrier.cidade,carrier.uf].filter(Boolean).join(" / ")]]}/><Info title="Contato e presença digital" rows={[["Site oficial",carrier.site],["Telefone",carrier.telefone],["E-mail",carrier.email_comercial],["Último enriquecimento",summary?.last_enrichment_at?new Date(summary.last_enrichment_at).toLocaleString("pt-BR"):null],["Próxima verificação",summary?.next_verification_at?new Date(summary.next_verification_at).toLocaleDateString("pt-BR"):null],["Score geral",score===null?null:`${score}%`],["Sucesso em cotações",carrier.taxa_sucesso?`${carrier.taxa_sucesso}%`:"Sem dados"],["Resposta média",carrier.tempo_medio_ms?`${carrier.tempo_medio_ms} ms`:"Sem dados"]]}/></div>}
      {!loading&&!error&&tab==="coverage"&&<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><Coverage title="Coleta" items={data.coverage.filter(x=>x.pickup_available)}/><Coverage title="Entrega" items={data.coverage.filter(x=>x.delivery_available)}/></div><div className="rounded border border-border p-4"><h3 className="text-sm font-medium">Testar cobertura</h3><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input value={origin} onChange={e=>setOrigin(e.target.value)} placeholder="CEP de origem"/><Input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="CEP de destino"/><button disabled={!origin||!destination} onClick={()=>void verify()} className="h-9 rounded bg-state-info px-4 text-sm text-white disabled:opacity-50">Verificar</button></div>{coverageResult&&<div className="mt-3 space-y-1 text-sm"><p>Coleta na origem: {coverageResult.pickup?"Sim":"Não"}</p><p>Entrega no destino: {coverageResult.delivery?"Sim":"Não"}</p><p className={coverageResult.eligible?"text-brand-copper":"text-state-warning"}>{coverageResult.eligible?"Transportadora apta para cotação.":"Transportadora não elegível para a rota."}</p></div>}</div></div>}
      {!loading&&!error&&tab==="integrations"&&<div className="grid gap-3 sm:grid-cols-2">{integrationCategories.map(([type,label])=>{const item=data.integrations.find(value=>value.integration_type===type);const confirmed=(item?.confidence_score||0)>=.9;return <div key={type} className="rounded border border-border p-4"><div className="flex justify-between gap-2"><b className="text-sm">{label}</b><Badge tone={item?confirmed?"success":"warning":"default"}>{item?confirmed?"Confirmada":"Possível":"Não encontrado"}</Badge></div>{item?<><p className="mt-3 text-xs text-text-secondary">Confiança: {Math.round((item.confidence_score||0)*100)}%</p><p className="mt-1 text-xs">Configurada: {configuredTypes.has(item.integration_type)?"Sim":"Não"}</p>{item.documentation_url&&<a className="mt-2 block truncate text-xs text-state-info underline" href={item.documentation_url} target="_blank" rel="noreferrer">Abrir fonte</a>}</>:<p className="mt-3 text-xs text-text-secondary">Nenhuma evidência suficiente foi localizada.</p>}<button onClick={onConfigure} className="mt-3 rounded border border-border px-3 py-1.5 text-xs">Configurar</button></div>})}</div>}
      {!loading&&!error&&tab==="branches"&&<div className="grid gap-3 sm:grid-cols-2">{data.branches.map(item=><div key={item.id} className="rounded border border-border p-4 text-sm"><b>{item.name}</b><p className="mt-2 text-text-secondary">{[item.city,item.uf].filter(Boolean).join(" / ")||"Localização não identificada"}</p><p>{item.cep||"CEP não identificado"}</p></div>)}{!data.branches.length&&<Empty text="Nenhuma filial identificada."/>}</div>}
      {!loading&&!error&&tab==="tables"&&<div className="space-y-3">{data.integrations.filter(x=>x.integration_type==="TABELA").map(item=><div key={item.id} className="rounded border border-border p-4"><b className="text-sm">Tabela detectada</b><p className="mt-1 text-xs text-text-secondary">{item.is_public?"Pública":"Privada ou autenticada"} · confiança {Math.round((item.confidence_score||0)*100)}%</p>{item.url&&<a href={item.url} target="_blank" rel="noreferrer" className="mt-2 block truncate text-xs text-state-info underline">{item.url}</a>}</div>)}<button onClick={onTables} className="rounded bg-state-info px-3 py-2 text-sm text-white">Gerenciar tabelas</button></div>}
      {!loading&&!error&&tab==="sources"&&<div className="space-y-4"><div className="space-y-2">{data.sources.map(item=><div key={item.id} className="rounded border border-border p-3 text-xs"><b>{item.tipo_fonte}</b>{item.url&&/^https:\/\//i.test(item.url)?<a href={item.url} target="_blank" rel="noreferrer" className="mt-2 inline-block rounded border border-border px-2 py-1 text-state-info">Abrir fonte</a>:<p className="mt-1 truncate text-text-secondary">{item.url||"Fonte sem URL"}</p>}<p className="mt-1 text-text-secondary">Confiança {Math.round((item.confidence_score||0)*100)}% · {item.data_pesquisa?new Date(item.data_pesquisa).toLocaleString("pt-BR"):"sem verificação"}</p></div>)}</div>{data.evidence.filter(x=>x.review_status==="PENDING").map(item=><div key={item.id} className="rounded border border-state-warning/30 p-3 text-xs"><b>Revisão necessária · {item.evidence_type}</b><p className="my-2 break-all">{item.value}</p><span>Confiança {Math.round(item.confidence_score*100)}%</span><div className="mt-2 flex gap-2"><button onClick={async()=>{const updated=await transportadoraService.revisarEvidencia(carrier.id,item.id,"APPROVED");setData(current=>({...current,evidence:current.evidence.map(x=>x.id===item.id?updated:x)}));}} className="rounded border border-border px-2 py-1">Aprovar</button><button onClick={async()=>{const corrected=window.prompt("Corrija o valor confirmado",item.value);if(corrected===null||!corrected.trim())return;const updated=await transportadoraService.revisarEvidencia(carrier.id,item.id,"APPROVED",corrected.trim());setData(current=>({...current,evidence:current.evidence.map(x=>x.id===item.id?updated:x)}));}} className="rounded border border-border px-2 py-1">Editar</button><button onClick={async()=>{const updated=await transportadoraService.revisarEvidencia(carrier.id,item.id,"REJECTED");setData(current=>({...current,evidence:current.evidence.map(x=>x.id===item.id?updated:x)}));}} className="rounded border border-border px-2 py-1">Rejeitar</button></div></div>)}</div>}
      {!loading&&!error&&tab==="performance"&&<Info title="Desempenho em cotações" rows={[["Taxa de sucesso",carrier.taxa_sucesso?`${carrier.taxa_sucesso}%`:"Sem dados"],["Tempo médio de resposta",carrier.tempo_medio_ms?`${carrier.tempo_medio_ms} ms`:"Sem dados"],["Status da integração",carrier.status_integracao||"Não identificado"]]}/>} 
    </div></section></div>;
}

function Info({title,rows}:{title:string;rows:Array<[string,string|null|undefined]>}){return <section><h3 className="mb-3 text-sm font-medium">{title}</h3><dl className="divide-y divide-border rounded border border-border">{rows.map(([label,value])=><div key={label} className="grid grid-cols-[130px_1fr] gap-3 p-3 text-xs"><dt className="text-text-secondary">{label}</dt><dd className="break-all">{value||"Não identificado"}</dd></div>)}</dl></section>}
function Coverage({title,items}:{title:string;items:EnrichmentCoverage[]}){return <section className="rounded border border-border p-4"><h3 className="text-sm font-medium">{title}</h3><div className="mt-3 space-y-2 text-xs">{items.map(item=><div key={item.id}>{item.coverage_type==="NATIONAL"?"Brasil":item.uf||item.city||`${item.cep_start} – ${item.cep_end}`} <span className="text-text-secondary">· {Math.round(item.confidence_score*100)}%</span></div>)}{!items.length&&<span className="text-text-secondary">Não identificada</span>}</div></section>}
function Empty({text}:{text:string}){return <p className="text-sm text-text-secondary">{text}</p>}
