import { Badge, Card } from "../../components/ui";
import type { CarrierCard } from "../../types/transportadora";

const statusLabels:Record<string,string>={NOT_STARTED:"Não iniciado",PROCESSING:"Processando",ENRICHED:"Completo",PARTIAL:"Parcial",WAITING_REVIEW:"Revisão necessária",NO_DATA:"Sem dados",ERROR:"Erro"};
const integrationLabels:Record<string,string>={API_REST:"API",API_SOAP:"SOAP",WEBSERVICE:"WebService",SSW:"SSW",SENIOR:"Senior",EDI:"EDI",PORTAL:"Portal",TABELA:"Tabela",EMAIL:"E-mail",WHATSAPP:"WhatsApp",MANUAL:"Manual"};
const stepLabels:Record<string,string>={queued:"Na fila",search_identity:"Pesquisando dados e fontes externas",crawl_official_site:"Analisando site oficial",detect_coverage:"Analisando cobertura e integrações",validate_and_save:"Validando e salvando evidências",completed:"Concluído",failed:"Falhou"};

interface Props { carrier:CarrierCard; enriching:boolean; jobProgress?:number; jobStep?:string|null; selected:boolean; onSelect:(selected:boolean)=>void; onDetails:()=>void; onConfigure:()=>void; onTables:()=>void; onEnrich:()=>void; onToggleStatus:()=>void; }

export function CarrierIntelligenceCard({carrier,enriching,jobProgress,jobStep,selected,onSelect,onDetails,onConfigure,onTables,onEnrich,onToggleStatus}:Props){
  const integrations=carrier.integrations.map(item=>item.type); const states=carrier.coverage.states; const processing=enriching||carrier.enrichment.status==="PROCESSING"; const percentage=processing&&jobProgress!=null?jobProgress:carrier.enrichment.percentage;
  return <Card className="flex min-h-[300px] flex-col !rounded-lg !shadow-none transition-colors hover:border-text-secondary/40">
    <div className="flex items-start gap-3"><input aria-label={`Selecionar ${carrier.nome}`} type="checkbox" checked={selected} onChange={event=>onSelect(event.target.checked)} className="mt-1 accent-state-info"/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h2 className="truncate text-sm font-semibold" title={carrier.nome}>{carrier.nome}</h2><Badge tone={carrier.ativa?"success":"warning"}>{carrier.ativa?"Ativa":"Inativa"}</Badge></div><p className="mt-1 truncate text-xs text-text-secondary">{carrier.razao_social}</p></div></div>
    <div className="mt-4 flex min-h-6 flex-wrap gap-1.5">{integrations.slice(0,4).map(type=><Badge key={type} tone="info">{integrationLabels[type]||type}</Badge>)}{integrations.length>4&&<Badge>+{integrations.length-4}</Badge>}{!integrations.length&&<span className="text-xs text-text-secondary">Integração não identificada</span>}</div>
    <div className="mt-4"><p className="text-[11px] font-medium uppercase tracking-wide text-text-secondary">Cobertura</p><p className="mt-1 text-sm">{carrier.coverage.national?"Brasil":states.length?[...states.slice(0,4),states.length>4?`+ ${states.length-4}`:""].filter(Boolean).join(" · "):"Não identificada"}</p>{carrier.has_freight_table&&<p className="mt-1 text-xs text-text-secondary">Tabela ativa</p>}</div>
    <div className="mt-4"><div className="flex justify-between text-xs"><span>Enriquecimento · {processing&&jobStep?(stepLabels[jobStep]||jobStep):(statusLabels[carrier.enrichment.status]||carrier.enrichment.status)}</span><span className="tabular-nums">{percentage}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-surface2"><div className="h-full bg-state-info transition-[width] duration-500" style={{width:`${percentage}%`}}/></div></div>
    <div className="mt-3 flex justify-between text-xs text-text-secondary"><span>{carrier.branches_count} filial(is)</span><span>{carrier.enrichment.last_run_at?`Atualizado ${new Date(carrier.enrichment.last_run_at).toLocaleDateString("pt-BR")}`:"Ainda não verificada"}</span></div>
    <div className="mt-auto grid grid-cols-2 gap-2 pt-5"><button onClick={onDetails} className="h-8 rounded border border-border text-xs hover:bg-surface2">Detalhes</button><button onClick={onConfigure} className="h-8 rounded border border-border text-xs hover:bg-surface2">Configurar</button><button onClick={onTables} className="h-8 rounded border border-border text-xs hover:bg-surface2">Gerenciar tabelas</button><button disabled={processing} onClick={onEnrich} className="h-8 rounded bg-state-info px-2 text-xs text-white disabled:opacity-50">{processing?"Processando...":carrier.enrichment.last_run_at?"Reprocessar":"Enriquecer"}</button><button onClick={onToggleStatus} className="col-span-2 h-8 rounded border border-border text-xs hover:bg-surface2">{carrier.ativa?"Desativar transportadora":"Ativar transportadora"}</button></div>
  </Card>;
}
