import { useMemo, useState } from "react";
import { Download, FileSpreadsheet, LoaderCircle, Search, Upload, X } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { Badge, Card, Input } from "../../components/ui";
import { getErrorMessage } from "../../api/client";
import { transportadoraService } from "../../services/transportadoraService";
import type { ImportacaoPreview, ImportacaoResultado, ResultadoImportacao } from "../../types/transportadora";

const tones:Record<ResultadoImportacao,"success"|"warning"|"error"|"default">={NOVO:"success",ATUALIZACAO:"warning",IGNORADO:"default",REVISAO:"warning",ERRO:"error",DUPLICADO:"error"};
const labels:Record<ResultadoImportacao,string>={NOVO:"Válido",ATUALIZACAO:"Já cadastrado",IGNORADO:"Já cadastrado",REVISAO:"Atenção",ERRO:"Inválido",DUPLICADO:"Duplicado"};

function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}

export function ImportarTransportadoras({onClose,onBack}:{onClose:()=>void;onBack?:()=>void}){
  const queryClient=useQueryClient();
  const [preview,setPreview]=useState<ImportacaoPreview|null>(null),[result,setResult]=useState<ImportacaoResultado|null>(null);
  const [filter,setFilter]=useState<ResultadoImportacao|"TODOS">("TODOS"),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const [updateExisting,setUpdateExisting]=useState(false),[review,setReview]=useState(false),[activate,setActivate]=useState(false),[enrich,setEnrich]=useState(false);
  async function select(file?:File){if(!file)return;setBusy(true);setMessage("");setResult(null);try{setPreview(await transportadoraService.previewImportacao(file))}catch(error){setMessage(getErrorMessage(error,"Não foi possível validar o arquivo."))}finally{setBusy(false)}}
  async function confirm(){if(!preview)return;setBusy(true);setMessage("");try{const response=await transportadoraService.confirmarImportacao(preview.import_id,updateExisting,review,activate);setResult(response);if(enrich&&response.transportadora_ids.length)await transportadoraService.enriquecerEmLote(response.transportadora_ids);await Promise.all([queryClient.invalidateQueries({queryKey:["transportadoras"]}),queryClient.invalidateQueries({queryKey:["transportadoras","cards"]}),queryClient.invalidateQueries({queryKey:["transportadoras","stats"]})])}catch(error){setMessage(getErrorMessage(error,"Não foi possível concluir a importação."))}finally{setBusy(false)}}
  async function template(){try{download(await transportadoraService.baixarModeloImportacao(),"modelo_transportadoras.csv")}catch(error){setMessage(getErrorMessage(error))}}
  async function report(){if(!result)return;try{download(await transportadoraService.baixarRelatorioImportacao(result.import_id),`relatorio_${result.import_id}.csv`)}catch(error){setMessage(getErrorMessage(error))}}
  const records=useMemo(()=>preview?.registros.filter(row=>(filter==="TODOS"||row.resultado===filter)&&(!search||`${row.nome_transportadora||""} ${row.cnpj||""} ${String(row.dados_normalizados.rntrc||"")}`.toLowerCase().includes(search.toLowerCase())))||[],[preview,filter,search]);
  const importable=(preview?.novos||0)+(review?preview?.revisao||0:0);
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/75 p-4 pt-[5vh]" role="dialog" aria-modal="true"><div className="mx-auto max-w-6xl overflow-hidden rounded-lg border border-border bg-surface shadow-2xl">
    <header className="flex items-start justify-between border-b border-border p-5"><div><h2 className="font-semibold">Importar de arquivo</h2><p className="mt-1 text-xs text-text-secondary">CSV ou Excel · validar antes de persistir</p></div><button onClick={onClose} aria-label="Fechar" className="rounded border border-border p-2"><X size={15}/></button></header>
    <div className="border-b border-border px-5 py-3 text-xs text-text-secondary"><span className="text-text-primary">1. Origem</span> · <span className={!preview?"text-state-info":"text-text-primary"}>2. Arquivo</span> · <span className={preview&&!result?"text-state-info":""}>3. Validar</span> · <span className={result?"text-state-info":""}>4. Importar</span></div>
    <div className="space-y-4 p-5">
      {!preview&&<Card className="!rounded-lg !shadow-none"><div className="flex flex-col items-center gap-3 py-8 text-center"><FileSpreadsheet className="text-state-info" size={30}/><div><p className="text-sm font-medium">Selecione um arquivo de transportadoras</p><p className="mt-1 text-xs text-text-secondary">CSV, XLSX ou XLS · máximo de 10 MB</p></div><label className="cursor-pointer rounded bg-state-info px-4 py-2 text-sm text-white"><Upload className="mr-2 inline" size={14}/>Selecionar arquivo<input className="sr-only" type="file" accept=".csv,.xlsx,.xls" disabled={busy} onChange={event=>void select(event.target.files?.[0])}/></label><button onClick={()=>void template()} className="inline-flex items-center gap-2 text-xs text-state-info"><Download size={13}/>Baixar modelo</button>{busy&&<span className="inline-flex items-center gap-2 text-sm"><LoaderCircle className="animate-spin" size={14}/>Validando arquivo...</span>}</div></Card>}
      {message&&<p role="alert" className="rounded border border-state-error/40 bg-state-error/10 p-3 text-sm text-state-error">{message}</p>}
      {result&&<Card className="!rounded-lg !shadow-none"><h3 className="font-semibold">Importação concluída</h3><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Cadastradas",result.resultado.criados||0],["Atualizadas",result.resultado.atualizados||0],["Ignoradas",result.resultado.ignorados||0],["Erros",result.resultado.erros||0]].map(([label,value])=><div key={label} className="rounded border border-border p-3"><p className="text-xs text-text-secondary">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div><div className="mt-4 flex flex-wrap justify-end gap-2"><button onClick={()=>void report()} className="inline-flex items-center gap-2 rounded border border-border px-3 py-2 text-sm"><Download size={14}/>Baixar relatório</button><button onClick={onClose} className="rounded bg-state-info px-4 py-2 text-sm text-white">Ver transportadoras</button></div></Card>}
      {preview&&!result&&<><div className="grid grid-cols-2 gap-2 md:grid-cols-6">{[["Total",preview.total],["Válidos",preview.novos],["Existentes",preview.atualizacoes+preview.ignorados],["Duplicados",preview.registros.filter(row=>row.resultado==="DUPLICADO").length],["Atenção",preview.revisao],["Inválidos",preview.erros]].map(([label,value])=><Card key={label} className="!rounded-lg !p-3 !shadow-none"><p className="text-xs text-text-secondary">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></Card>)}</div>
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2">{(["TODOS","NOVO","ATUALIZACAO","REVISAO","ERRO","DUPLICADO"] as const).map(value=><button key={value} className={`rounded border px-3 py-1.5 text-xs ${filter===value?"border-state-info bg-state-info/10":"border-border"}`} onClick={()=>setFilter(value)}>{value==="TODOS"?"Todos":labels[value]}</button>)}</div><label className="relative"><Search className="absolute left-3 top-2.5 text-text-secondary" size={14}/><Input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Nome, CNPJ ou RNTRC" className="pl-8 sm:w-64"/></label></div>
        <div className="max-h-[45vh] overflow-auto rounded border border-border"><table className="w-full min-w-[850px] text-xs"><thead className="sticky top-0 bg-surface2"><tr className="text-left"><th className="p-3">Status</th><th>CNPJ</th><th>Razão social</th><th>Nome fantasia</th><th>RNTRC</th><th>Cidade</th><th>UF</th><th>Motivo</th></tr></thead><tbody>{records.map(row=><tr key={row.linha} className="border-t border-border"><td className="p-3"><Badge tone={tones[row.resultado]}>{labels[row.resultado]}</Badge></td><td>{row.cnpj||"—"}</td><td>{String(row.dados_normalizados.razao_social||"—")}</td><td>{row.nome_transportadora||"—"}</td><td>{String(row.dados_normalizados.rntrc||"—")}</td><td>{String(row.dados_normalizados.cidade||"—")}</td><td>{String(row.dados_normalizados.uf||"—")}</td><td className="max-w-56 truncate">{[...row.erros,...row.avisos].join("; ")||"—"}</td></tr>)}</tbody></table></div>
        <div className="grid gap-2 rounded border border-border p-3 text-sm sm:grid-cols-2"><label><input type="checkbox" checked={updateExisting} onChange={event=>setUpdateExisting(event.target.checked)}/> Atualizar somente dados cadastrais existentes</label><label><input type="checkbox" checked={review} onChange={event=>setReview(event.target.checked)}/> Importar registros com atenção</label><label><input type="checkbox" checked={activate} onChange={event=>setActivate(event.target.checked)}/> Ativar transportadoras importadas</label><label><input type="checkbox" checked={enrich} onChange={event=>setEnrich(event.target.checked)}/> Enriquecer novas transportadoras agora</label></div>
        <div className="flex flex-wrap justify-between gap-3"><button onClick={()=>{setPreview(null);setMessage("")}} className="rounded border border-border px-4 py-2 text-sm">Selecionar outro arquivo</button><div className="flex gap-2">{onBack&&<button onClick={onBack} className="rounded border border-border px-4 py-2 text-sm">Voltar</button>}<button disabled={busy||importable===0} onClick={()=>void confirm()} className="rounded bg-state-info px-4 py-2 text-sm text-white disabled:opacity-50">{busy?"Importando...":`Importar ${importable} transportadora(s)`}</button></div></div></>}
    </div>
  </div></div>
}
